In [2]:
import pandas as pd

In [6]:
lcn = pd.read_csv(r"C:\Users\HP\Downloads\LungCapData.csv")

In [7]:
lcn.head(2)

,LungCap,Age,Height,Smoke,Gender,Caesarean
0,6.475,6,62.1,no,male,no
1,10.125,18,74.7,yes,female,no


In [8]:
lcn.isnull().sum()

LungCap      0
Age          0
Height       0
Smoke        0
Gender       0
Caesarean    0
dtype: int64

In [9]:
lcn['Smoke'] = lcn['Smoke'].replace({'no':0 , 'yes':1})

C:\Users\HP\AppData\Local\Temp\ipykernel_13140\867839690.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  lcn['Smoke'] = lcn['Smoke'].replace({'no':0 , 'yes':1})


In [10]:
lcn['Gender'] = lcn['Gender'].replace({'female':0, 'male':1})

C:\Users\HP\AppData\Local\Temp\ipykernel_13140\55842492.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  lcn['Gender'] = lcn['Gender'].replace({'female':0, 'male':1})


In [13]:
lcn['Caesarean'] = lcn['Caesarean'].replace({'no':0, 'yes':1})

C:\Users\HP\AppData\Local\Temp\ipykernel_13140\993802780.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  lcn['Caesarean'] = lcn['Caesarean'].replace({'no':0, 'yes':1})


In [14]:
lcn.head()

,LungCap,Age,Height,Smoke,Gender,Caesarean
0,6.475,6,62.1,0,1,0
1,10.125,18,74.7,1,0,0
2,9.550,16,69.7,0,0,1
3,11.125,14,71.0,0,1,0
4,4.800,5,56.9,0,1,0


In [15]:
# to build a predictive model which will predict the lung capacity

In [25]:
from sklearn.model_selection import train_test_split
lcn_train , lcn_test = train_test_split(lcn, test_size= .2)
lcn_train_x = lcn_train.iloc[: , 1::]
lcn_train_y = lcn_train.iloc[: , 0]

lcn_test_x = lcn_test.iloc[: , 1::]
lcn_test_y = lcn_test.iloc[: , 0]

In [32]:
from sklearn.linear_model import LinearRegression
linreg = LinearRegression()
linreg.fit(lcn_train_x , lcn_train_y)
Rsqu= linreg.score(lcn_train_x , lcn_train_y)
Rsqu

0.8612502935735971

In [35]:
N = lcn_train_x.shape[0]
K = lcn_train_x.shape[1]
AdjRsquare = 1 -(1-Rsqu) *(N-1) / (N-K-1)
AdjRsquare

0.8600416724374785

In [27]:
linreg.coef_

array([ 0.17702848,  0.25917025, -0.51357802,  0.38123607, -0.27299704])

In [28]:
lcn_train_x.columns

Index(['Age', 'Height', 'Smoke', 'Gender', 'Caesarean'], dtype='object')

In [29]:
linreg.intercept_

np.float64(-11.204886170188942)

In [30]:
pred_test = linreg.predict(lcn_test_x)
pred_train = linreg.predict(lcn_train_x) 

In [31]:
pred_test

array([ 6.06943205,  6.14610127,  7.22691676,  4.19505205,  4.14087405,
       11.6085135 , 10.68554411,  7.96425653,  9.88589965,  9.07779826,
        3.91831901,  8.45210906,  8.0044275 ,  3.35566377,  5.11050214,
       10.46209875,  4.88055776,  9.73539559,  4.77358082, 11.311336  ,
       12.10724446,  8.18915551,  8.99323797,  7.52787757,  7.49756985,
        7.07015252,  8.43184483,  6.49245868,  9.92223193,  9.83569947,
        9.79119318,  8.80551131,  7.16503923,  7.97742862,  5.47646909,
        3.14393688, 11.01037519,  7.8484982 ,  6.14153034,  6.80785367,
        8.07213509,  7.80021991,  8.65944526,  3.92710041,  7.92228573,
        9.12613194,  5.92541275,  6.37478356,  6.91483061,  8.69414368,
       10.05018319, 10.42950247,  4.4485695 ,  7.20099974,  2.60846076,
        2.7608343 ,  8.86841532, 11.42378549,  6.20298072, 10.77164942,
        7.94254996,  8.14549546, 11.46810024,  6.23202634, 10.99323956,
        8.28404222,  9.58806745,  6.0721335 ,  7.43299087,  7.62

In [40]:
import numpy as np

In [42]:
pred_test = linreg.predict(lcn_test_x)
error_train = lcn_train_y - pred_train
mse_train = np.mean(np.square(error_train))
mse_train

np.float64(1.0063047196683677)

In [43]:
np.sqrt(mse_train)

np.float64(1.0031474067495603)

In [44]:
from sklearn.metrics import mean_squared_error

mean_squared_error(lcn_train_y , pred_train)

1.0063047196683677

In [47]:
from sklearn.metrics import root_mean_squared_error

root_mean_squared_error(lcn_train_y , pred_train)

1.0031474067495603

In [49]:
from sklearn.metrics import mean_absolute_percentage_error
mean_absolute_percentage_error(lcn_train_y , pred_train)* 100

13.217811557525938

In [50]:
mt = pd.read_csv(r"C:\Users\HP\Downloads\Mtcars.csv")

In [52]:
mt.head()

,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
0,21.0,6,160.0,110,3.90,2.620,16.46,0,1,4,4
1,21.0,6,160.0,110,3.90,2.875,17.02,0,1,4,4
2,22.8,4,108.0,93,3.85,2.320,18.61,1,1,4,1
3,21.4,6,258.0,110,3.08,3.215,19.44,1,0,3,1
4,18.7,8,360.0,175,3.15,3.440,17.02,0,0,3,2


In [53]:
mt.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32 entries, 0 to 31
Data columns (total 11 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   mpg     32 non-null     float64
 1   cyl     32 non-null     int64  
 2   disp    32 non-null     float64
 3   hp      32 non-null     int64  
 4   drat    32 non-null     float64
 5   wt      32 non-null     float64
 6   qsec    32 non-null     float64
 7   vs      32 non-null     int64  
 8   am      32 non-null     int64  
 9   gear    32 non-null     int64  
 10  carb    32 non-null     int64  
dtypes: float64(5), int64(6)
memory usage: 2.9 KB


In [54]:
mt.isnull().sum()

mpg     0
cyl     0
disp    0
hp      0
drat    0
wt      0
qsec    0
vs      0
am      0
gear    0
carb    0
dtype: int64

In [56]:
from sklearn.model_selection import train_test_split
mt_train , mt_test = train_test_split(lcn, test_size= .2)
mt_train_x = mt_train.iloc[: , 1::]
mt_train_y = mt_train.iloc[: , 0]

In [57]:
mt_test_x = mt_test.iloc[: , 1::]
mt_test_y = mt_test.iloc[: , 0]

In [58]:
from sklearn.linear_model import LinearRegression
linreg = LinearRegression()
linreg.fit(mt_train_x , mt_train_y)
Rsqu= linreg.score(mt_train_x , mt_train_y)
Rsqu

0.8584141420836235

In [59]:
N = mt_train_x.shape[0]
K = mt_train_x.shape[1]
AdjRsquare = 1 -(1-Rsqu) *(N-1) / (N-K-1)
AdjRsquare

0.8571808157951534

In [62]:
pred_test = linreg.predict(mt_test_x)
pred_train = linreg.predict(mt_train_x) 

In [63]:
pred_test

array([ 8.51519895,  7.9269214 , 10.9309394 , 10.32540265,  9.92698457,
       13.09285413, 10.1438205 ,  5.1685823 ,  5.57644816,  8.66005655,
        5.75759524,  7.32134958,  6.58925013, 10.77693435, 12.44030999,
       10.46767104, 12.34973645,  8.49646898,  7.70237372, 10.96549286,
        9.24813347,  6.50812435,  4.42763572,  7.90017937,  8.06333187,
        7.69075486,  5.71102292,  8.42432509,  8.40776621,  8.28078538,
        7.08478305,  7.25895377, 10.83255443, 10.57882838,  9.86325274,
        4.94333431,  3.85621736,  8.8775928 ,  6.50708865, 11.30136226,
        8.46205027,  1.93086917,  6.48054725, 10.92282765,  2.51771102,
        7.63924252,  9.70912988,  9.20247905,  6.29158873,  7.33994479,
        6.59839757,  9.51070665,  7.73794475, 10.01799318,  9.584021  ,
       11.41949596, 11.41949596,  6.37241419,  6.5172718 ,  7.70195559,
        6.17357284,  5.17772975, 11.62678444,  6.27010399,  3.02539755,
       10.29814281, 12.46858741,  8.93014085,  7.97349371, 11.15

In [64]:
err_train = mt_train_y - pred_train 

In [67]:
import numpy as np


In [68]:
mse = np.mean(np.square(err_train))

In [69]:
mse

np.float64(1.014790281559299)

In [72]:
from sklearn.metrics import mean_absolute_percentage_error
mape = mean_absolute_percentage_error(mt_train_y,pred_train)

In [71]:
from sklearn.metrics import root_mean_squared_error
root_mean_squared_error(mt_train_y,pred_train)

1.007367997089097

In [73]:
acc=100 - mape

In [74]:
acc

99.87136777274736